cool_stocks_app/config/routes.rb
Rails.application.routes.draw do
  # get 'portfolios/index'
  # get 'portfolios/show'
  # get 'portfolios/new'
  # get 'portfolios/create'
  # get 'portfolios/edit'
  # get 'portfolios/update'
  # get 'portfolios/destroy'
  # get 'investors/index'
  # get 'investors/show'
  # get 'investors/new'
  # get 'investors/create'
  # get 'investors/edit'
  # get 'investors/update'
  # get 'investors/destroy'
  # get 'stocks/index'
  # get 'stocks/show'
  # get 'stocks/new'
  # get 'stocks/create'
  # get 'stocks/edit'
  # get 'stocks/update'
  # get 'stocks/destroy'
  get "/", to: "application#homepage", as: "index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :stocks, :investors, :portfolios

end

cool_stocks_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cool_stocks_app/app/models/investor.rb
class Investor < ApplicationRecord
    has_many :portfolios
    has_many :stocks, through: :portfolios
    accepts_nested_attributes_for :portfolios

end

cool_stocks_app/app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :investor
    belongs_to :stock
    
end

cool_stocks_app/app/models/stock.rb
class Stock < ApplicationRecord
    has_many :portfolios
    has_many :investors, through: :portfolios
end

cool_stocks_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index
    end
end

cool_stocks_app/app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
 
 before_action :find_investor, only: [:show, :edit, :update, :destroy]

  def index
    @investors = Investor.all
  end

  def show 
    
  end

  def new
    @investor = Investor.new
  end

  def create
    investor = Investor.create(investor_params)
    redirect_to investor_path(investor)
  end

  def edit
  end

  def update
    stock = Stock.find(params[:investor][:portfolio][:stock_id])
    @investor.stocks << stock
    
    @investor.update(investor_params)
    redirect_to investor_path(@investor)
  end

  def destroy
    @investor.destroy
    redirect_to investors_path
  end

  private 

  def investor_params
    params.require(:investor).permit(:name, :company)
  end

  def find_investor 
    @investor = Investor.find(params[:id])
  end


end

cool_stocks_app/app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

cool_stocks_app/app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  before_action :find_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = Stock.all 
  end

  def show
  end

  def new
    @stock = Stock.new 
  end

  def create
    stock = Stock.create(stocks_params)
    redirect_to stock_path(stock)
  end

  def edit

  end

  def update
    @stock.update(stocks_params)
    redirect_to stock_path(@stock)
  end

  def destroy
    @stock.destroy
    redirect_to stocks_path
  end

  private 

  def stocks_params
    params.require(:stock).permit(:name, :price, :description)
  end 

  def find_stock
    @stock = Stock.find(params[:id])
  end 

end

cool_stocks_app/app/helpers/application_helper.rb
module ApplicationHelper
end

cool_stocks_app/app/helpers/investors_helper.rb
module InvestorsHelper
end

cool_stocks_app/app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

cool_stocks_app/app/helpers/stocks_helper.rb
module StocksHelper
end

cool_stocks_app/app/views/application/homepage.html.erb
<h1>Welcome to our Cool Stock APP!</h1>

<br>


<h4><%= link_to 'To Investors Index', investors_path %></h4>
<br>
<h4><%= link_to "The Stocks Page", stocks_path%></h4>

cool_stocks_app/app/views/investors/_investor_form.html.erb
<%= form_for (@investor) do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name %>
    <%=f.label :company %>
    <%=f.collection_select :company, Investor.all, :company, :company %>
    <br>
    <h4>Add Stocks to Your Portfolio</h4>
    <%=f.fields_for :portfolio do |s| %>
      <div>
                <%= s.label :stock_id%>
                <%= s.collection_select :stock_id, Stock.all, :id, :name, {prompt: "Choose a Stock"}  %>
            </div>
        <% end %>
    <%= f.submit %>
<% end %>

cool_stocks_app/app/views/investors/edit.html.erb
<h1>Edit an investor</h1>

<%= render partial: "investor_form" %>

cool_stocks_app/app/views/investors/index.html.erb
<h1>All the Investors</h1>

<ul>
<% @investors.each do |investor| %>
    <li><%= link_to investor.name, investor_path(investor) %></li>
<% end %>  
</ul>

<%=link_to "Create an investor", new_investor_path%>
<br>
<h3><%= link_to "HOMEPAGE", index_path %></h3>

cool_stocks_app/app/views/investors/new.html.erb
<%= render partial: "investor_form" %>

cool_stocks_app/app/views/investors/show.html.erb
<h1>Investor</h1>

<h3>Name: <%= @investor.name%></h3>

<h4>Company: <%=@investor.company%></h4>
<%= link_to "Portfolio", portfolio_path(@investor) %>
<ul>
    <%@investor.stocks.each do |stock| %>
        <li><%= link_to stock.name, stock_path(stock)%></li>
    <%end%>
</ul>
<br>
<%= link_to 'Edit an investor', edit_investor_path(@investor) %><br><br>
<%= link_to 'Back to Investors Index', investors_path %>

<%= form_tag investor_path(@investor), method: "DELETE" do %>
    <%= submit_tag "DELETE the investor"%>
<% end %>

cool_stocks_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolStocksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cool_stocks_app/app/views/portfolios/create.html.erb
<h1>Portfolios#create</h1>
<p>Find me in app/views/portfolios/create.html.erb</p>

cool_stocks_app/app/views/portfolios/destroy.html.erb
<h1>Portfolios#destroy</h1>
<p>Find me in app/views/portfolios/destroy.html.erb</p>

cool_stocks_app/app/views/portfolios/edit.html.erb
<h1>Portfolios#edit</h1>
<p>Find me in app/views/portfolios/edit.html.erb</p>

cool_stocks_app/app/views/portfolios/index.html.erb
<h1>Portfolios#index</h1>
<p>Find me in app/views/portfolios/index.html.erb</p>

cool_stocks_app/app/views/portfolios/new.html.erb
<h1>Portfolios#new</h1>
<p>Find me in app/views/portfolios/new.html.erb</p>

cool_stocks_app/app/views/portfolios/show.html.erb
<h1>Portfolios#show</h1>


<%= @investor.name %>

cool_stocks_app/app/views/portfolios/update.html.erb
<h1>Portfolios#update</h1>
<p>Find me in app/views/portfolios/update.html.erb</p>

cool_stocks_app/app/views/stocks/_stocks_form.html.erb
<%= form_for @stock do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :price %>
    <%= f.number_field :price%><br>
    <%= f.label :description %>
    <%= f.text_area :description%><br>
    <%= f.submit %>

<% end %>

cool_stocks_app/app/views/stocks/edit.html.erb
<h1>Edit Stock </h1> 

<%= render partial: "stocks_form" %>

cool_stocks_app/app/views/stocks/index.html.erb
<h1>Stocks Homepage</h1>
<ul>
    <% @stocks.each do |stock| %> 
        <li><%= link_to stock.name, stock_path(stock) %></li>
    <% end %> 
</ul>

<%= link_to "Create a stock", new_stock_path %>

<br>
<h3><%= link_to "HOMEPAGE", index_path %></h3>

cool_stocks_app/app/views/stocks/new.html.erb
<h1>Stock Form</h1>

<%= render partial: "stocks_form" %>

cool_stocks_app/app/views/stocks/show.html.erb
<h1><%=@stock.name%></h1>
<h3><%=@stock.price%></h3>
<h4><%=@stock.description%></h4><br>

<%= link_to "Edit Stock", edit_stock_path %><br>
<%= link_to "Stocks Homepage", stocks_path %>

<%= form_tag stock_path(@stock), method: "delete" do %>
    <%= submit_tag "Delete Stock" %>
<% end %>